<h2><i class="fa fa-lock"></i> Se connecter avec un compte utilisateur</h2>

<form class="generic-form" method="POST" action="<?=$requestUrl?>/user/login">
<aside class="error-message hidden">
    <h3><i class="fa fa-warning"></i> Il y a
      <span id="total-error-count">1</span> erreur(s) dans le formulaire !
    </h3>
    <p><?=$errorMessage ?></p>
  </aside>
 	  <fieldset>
    <legend>Informations d'authentification</legend>
    <ul>
      <li>
        <label for="Email">E-mail :</label>
        <input id="Email" type="text" name="Email" data-required data-name="E-mail" value="<?=$Email?>">
      </li>
      <li>
        <label for="Password">Mot de passe :</label>
        <input id="Password" type="password" name="Password" data-required data-name="Mot de passe">
      </li>
    </ul>
  </fieldset>

  <ul>
    <li>
      <input class="button button-primary" type="submit" value="Connexion">
      <a class="button button-cancel small" href="<?= $requestUrl ?>">Annuler</a>
    </li>
  </ul>
</form>