<h2><i class="fa fa-lock"></i> Réservation d'une table</h2>

<form class="generic-form" method="POST" action="<?=$requestUrl?>/booking">
<aside class="error-message hidden">
    <h3><i class="fa fa-warning"></i> Il y a
      <span id="total-error-count">1</span> erreur(s) dans le formulaire !
    </h3>
    <p></p>
  </aside>
 	  <fieldset>
    <legend>Informations</legend>
    <ul>
      <li>
      <label for="date">Date de reservation: </label>
          <span>
             <select name="day">

              <?php for($j = 1; $j <=31 ;$j++):?>
                <?php if($j == date('d')) :?>
                <option selected value="<?= $j ?>"><?=$j ?></option>
                <?php else : ?>
                  <option value='<?= $j ?>'><?=$j?></option>
                <?php endif;?> 
              <?php endfor;?>  

             </select>
        </span> /
        <span>
          <select name="month">
              <?php $months = ['01' =>'January','02'=>'February','03'=>'March','04'=>'April','05'=>'May',
                            '06'=>'June','07'=>'July','08'=>'August','09'=>'September','10'=>'October',
                             '11'=>'November','12'=>'December'];

                            foreach ($months as $key => $value) :?>

                            <option value="<?=$key ?>"><?=$value?></option>
                                
                            <?php endforeach ?>

         </select> 
      </span>/

      <span>
           <select name="year">
            <?php ;
             for($year=2019; $year<=2020; $year++): ?>
              <option value="<?=$year?>"><?=$year?></option>
             <?php endfor; ?>    
           </select>
      </span><span> à </span>

      <span>
           <select name="time">
            <?php 
             for($time=12; $time<=23; $time++): ?>
              <option value="<?=$time?>"><?=$time?></option>
             <?php endfor; ?>    
           </select>
      </span>:
       <span>
           <select name="minute">
          
              <option value="00">00</option>
              <option value="15">15</option>
              <option value="30">30</option>
              <option value="45">45</option>
               
           </select>
      </span>
      </li>
      <li>
           <span>
            <label for="couvert">Nombre de couvert: </label>

            <select name="couvert">
          
              <option value="1">1</option>
              <option value="2">2</option>
              <option value="3">3</option>
              <option value="4">4</option>
              <option value="5">5</option>
              <option value="6">6</option>

               
            </select>
      </span>
     
      </li>
    
    </ul>
  </fieldset>

  <ul>
    <li>
      <input class="button button-primary" type="submit" value="Reserver">
      <a class="button button-cancel small" href="<?= $requestUrl ?>">Annuler</a>
    </li>
  </ul>
</form>