<h2><i class="fa fa-lock"></i> Passer une commande</h2>

<form id="order-form"> class="generic-form" method="POST" action="<?=$requestUrl?>/order">

 	  <fieldset>
    <legend>Ajouter un article</legend>
    <ul>
      <li>
          <label for="images">Nom </label>
           <span>
             <select id="meal" name="meals">

                <?php foreach ($meals as $meal): ?>
              
                  <option value="<?=$meal['Id']?>"><?=$meal['Name']?></option>

                <?php endforeach;?>

             </select>
           </span>
      </li>

      <li>

          
              <aside id="meal-details" class="meal-details">
                  <img src="" alt="">
                  <p></p>
                  <p><span>Prix:</span><strong>3,00€</strong></p>
              </aside>
              
          
      </li>
      <li>
        <label for="QuantityOrdered">Quantité :</label>
        <input type="text" class="quantity" name="QuantityOrdered">
      </li>
      <li>
      <input id="validate-order" class="button button-primary" type="submit" value="Ajouter">
     
    </li>
    </ul>
  </fieldset>

  <fieldset>
    <legend>Récapitulatif de la commande</legend>
    <!-- Message de notification -->
    
    <p id="order-summary"></p>
      
  </fieldset>

 
  </ul>
</form>

